[package]
name = "jump-kun-macros"
version = "0.1.4"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A crate for jump-kun. Parses jump-kun config file and creates fucntions."
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.33", features = ["extra-traits", "full"] }
proc-macro2 = "1.0.18"
quote = "1.0.7"
toml = "0.5.6"
dirs = "3.0.0"
