[package]
name = "jump-kun-macros"
version = "0.1.11"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A crate for jump-kun. Parses jump-kun config file and creates fucntions."
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.76", features = ["extra-traits", "full"] }
proc-macro2 = "1.0.29"
quote = "1.0.9"
toml = "0.5.8"
dirs = "4.0.0"
