[package]
name = "jump-kun-macros"
version = "0.1.0"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version =  "0.15.42", features = ["extra-traits", "full"] }
proc-macro2 = "0.4.30"
quote = "0.6.12"
toml = "0.4.2"
dirs = "2.0.2"
