[package]
name = "jump-kun"
version = "0.4.8"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A simple directory jumper made by rust."
repository = "https://github.com/TakaakiFuruse/jump-kun"
license = "MIT"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={version = "0.1.1", path = "jump-kun-macros"}
jwalk= "0.6.0"
skim = "0.9.4"
serde_json= "1.0.64"
serde = { version = "1.0.124", features = ["derive"] }
dirs = "3.0.1"
sled = "0.34.6"
ignore = "0.4.17"
anyhow = "1.0.38"
