[package]
name = "jump-kun"
version = "0.3.1"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A simple directory jumper made by rust."
repository = "https://github.com/TakaakiFuruse/jump-kun"
license = "MIT"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={version = "0.1.0", path = "jump-kun-macros"}
walkdir= "2.2.9"
skim = "0.6.9"
serde_json= "1.0.41"
serde = { version = "1.0.101", features = ["derive"] }
dirs = "2.0.2"
derive_builder = "0.8.0"
sled = "0.28.0"
ignore = "0.4.10"
