[package]
name = "jump-kun"
version = "0.1.0"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
walkdir="2.2.7"
"skim" = { git = "https://github.com/lotabout/skim" }
serde_json="1.0.39"
serde = {version = "1.0.92", features = ["derive"] }
dirs = "2.0.1"