[package]
name = "jump-kun"
version = "0.4.0"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A simple directory jumper made by rust."
repository = "https://github.com/TakaakiFuruse/jump-kun"
license = "MIT"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={version = "0.1.1", path = "jump-kun-macros"}
jwalk= "0.5.1"
skim = "0.8.2"
serde_json= "1.0.55"
serde = { version = "1.0.114", features = ["derive"] }
dirs = "3.0.0"
sled = "0.32.0"
ignore = "0.4.16"
anyhow = "1.0.31"
