[package]
name = "jump-kun"
version = "0.1.0"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={path = "jump-kun-macros"}
walkdir="2.2.9"
skim = "0.6.8"
serde_json="1.0.40"
serde = {version = "1.0.99", features = ["derive"] }
dirs = "2.0.2"
derive_builder = "0.7.2"
sled = "0.26"