[package]
name = "jump-kun"
version = "0.4.5"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A simple directory jumper made by rust."
repository = "https://github.com/TakaakiFuruse/jump-kun"
license = "MIT"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={version = "0.1.1", path = "jump-kun-macros"}
jwalk= "0.5.1"
skim = "0.9.2"
serde_json= "1.0.59"
serde = { version = "1.0.117", features = ["derive"] }
dirs = "3.0.1"
sled = "0.34.4"
ignore = "0.4.16"
anyhow = "1.0.33"
