[package]
name = "jump-kun"
version = "0.3.5"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A simple directory jumper made by rust."
repository = "https://github.com/TakaakiFuruse/jump-kun"
license = "MIT"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={version = "0.1.1", path = "jump-kun-macros"}
walkdir= "2.3.1"
skim = "0.8.0"
serde_json= "1.0.48"
serde = { version = "1.0.104", features = ["derive"] }
dirs = "2.0.2"
sled = "0.31.0"
ignore = "0.4.11"
anyhow = "1.0.26"
