[package]
name = "jump-kun"
version = "0.2.0"
authors = ["TakaakiFuruse <takaakifuruse@gmail.com>"]
edition = "2018"
description = "A simple directory jumper made by rust."
repository = "https://github.com/TakaakiFuruse/jump-kun"
license = "MIT"

[[bin]]
name = "jump-kun"
path = "src/main.rs"

[dependencies]
jump-kun-macros={version = "0.1.0", path = "jump-kun-macros"}
walkdir="2.2.9"
skim = "0.6.8"
serde_json="1.0.40"
serde = {version = "1.0.99", features = ["derive"] }
dirs = "2.0.2"
derive_builder = "0.7.2"
sled = "0.27"
ignore = "0.4.10"
